<div>
    <div ng-if="status === 'failed'">
        <div ng-switch="innerException.ExceptionType || innerException.ClassName">
            <ud-collision-error
                ng-switch-when="Umbraco.Deploy.Exceptions.ArtifactCollisionException"
                operation="operation"
                exception-udis="exceptionUdis"
                exception="innerException">
            </ud-collision-error>

            <ud-deploy-schema-mismatch-error
                ng-switch-when="Umbraco.Deploy.Exceptions.DeploySchemaMismatchException"
                exception="innerException">
            </ud-deploy-schema-mismatch-error>

            <ud-restore-schema-mismatch-error
                ng-switch-when="Umbraco.Deploy.Exceptions.RestoreSchemaMismatchException"
                exception="innerException"
                no-nodes="noNodes">
            </ud-restore-schema-mismatch-error>

            <div class="ud-unauthorizedclient-error" ng-switch-when="Umbraco.Deploy.Exceptions.UnauthorizedClientException">
                <h4 class="bold color-red">Authorization error</h4>
                <p>Authorization between your environments has failed.</p>
                <p>
                    This could be caused by having different deploy API keys configured for each of your environments.
                    API keys are specified by the "Umbraco.Deploy.ApiKey" application setting in web.config.
                    Please ensure that these settings match before trying to continue.
                </p>
            </div>

            <div class="ud-kabum-error" ng-switch-when="Umbraco.Deploy.Exceptions.KabumException">
                <h4 class="bold color-red">Kabum! &#128163; &#128035;</h4>
                <p>
                    This error was triggered by having this configuration setting in your <em>{{exception.EnvironmentName}}</em> environment,
                    and deploying a content item with a name ending with <code>&lt;value&gt;</code>&nbsp;:
                </p>
                <pre>
                    &lt;settings&gt;
                    &nbsp;&nbsp;&nbsp;&nbsp;&lt;deploy kabum=&quot;&lt;value&gt;&quot;&nbsp;/&gt;
                    &lt;/settings&gt;
                </pre>
                <p>
                    This is used for debugging exceptions &amp; errors and should normally not appear unless you are debugging something.
                    You can disable it by removing the "kabum" attribute from the UmbracoDeploy.settings.config file in ~/config of your site.
                </p>
                <div ng-if="exceptionUdis.length>0">
                    <p>The following artifacts might be involved:</p>
                    <ul ng-repeat="udi in exceptionUdis">
                        <li>{{udi}}</li>
                    </ul>
                </div>
            </div>

            <div class="ud-content-type-changed-error" ng-switch-when="Umbraco.Deploy.Exceptions.ContentTypeChangedException">
                <h4 class="bold color-red">Unsupported content type change</h4>
                <p>
                    The content type of a document or media you are trying to transfer, has changed. This means that the item exists
                    on both sites, but with a different content type. Deploying content type changes is currently not supported by
                    Umbraco Deploy.
                </p>
                <p>
                    If you want to transfer this document, you need to delete the existing document in the destination site and
                    redeploy it from the source site using the new document type.
                </p>
                <div ng-if="exceptionUdis.length>0">
                    <p>The following artifacts might be involved:</p>
                    <ul ng-repeat="udi in exceptionUdis">
                        <li>{{udi}}</li>
                    </ul>
                </div>
            </div>

            <div class="ud-dependency-error" ng-switch-when="Umbraco.Deploy.Exceptions.DependencyException">
                <h4 class="bold color-red">Dependency Error</h4>
                <p>{{exception.Message}}</p>
                <p>This situation must be fixed before deploy can work.</p>
            </div>

            <div class="ud-busy-error" ng-switch-when="Umbraco.Deploy.Exceptions.EnvironmentBusyException">
                <h4 class="bold color-red">A content transfer is already in progress</h4>
                <p>
                    Another content transfer has already been started, by <strong>{{exception.UserName}}</strong> <em>({{exception.UserEmail}})</em>.
                    Please try your content transfer again later.
                </p>
            </div>

            <div class="ud-chunkedencoding-error" ng-switch-when="Umbraco.Deploy.Exceptions.ChunkedEncodingException">
                <h4 class="bold color-red">Unable to open session</h4>
                <p>Deploy was unable to open a session to the remote environment due to a problem with chunked transfer encoding.</p>
                <p>
                    Chunked transfer encoding is incompatible with Deploy and is usually caused by using an upgraded version
                    of the <em>System.Net.Http</em> assembly in your project.
                </p>
                <p>
                    Please ensure that your assembly redirect bindings for <em>System.Net.Http</em> are set to version <em>4.0.0.0</em>
                    in the <em>Web.config</em> of all of your environments.
                </p>
            </div>

            <div class="ud-webexception-error" ng-switch-when="System.Net.WebException">
                <h4 class="bold color-red">Connection error</h4>
                <p>{{innerException.Message}}</p>
            </div>

            <div class="ud-invalid-path-error" ng-switch-when="Umbraco.Deploy.Exceptions.InvalidPathException">
                <h4 class="bold color-red">Invalid Path in data</h4>
                <p>
                    During the deploy process, an invalid path was found in the database.
                    This can be fixed by updating the paths in <em>umbracoNode</em> to be correct.
                    Please contact support for instructions on how to solve this issue.
                </p>
                <div ng-if="exceptionUdis.length>0">
                    <p>The following artifacts might be involved:</p>
                    <ul ng-repeat="udi in exceptionUdis">
                        <li>{{udi}}</li>
                    </ul>
                </div>
            </div>

            <div class="ud-merge-conflict-error" ng-switch-when="Umbraco.Deploy.Exceptions.MergeConflictException">
                <h4 class="bold color-blue">Merge Conflict</h4>
                <p>
                    The following file found contains the merge conflict that needs to be fixed with your Git merge tool of choice:<br />
                    <pre>/data/revisions/{{exception.FileName}}</pre>
                </p>
                <h4 class="ud-merge-conflict-error__header">How did I get a merge conflict?</h4>
                <p>
                    A common merge conflict happens when yourself or another developer adds a new property to a document type directly on the Cloud site and you
                    forget to pull down the latest changes from the Git repository and decide to work on the same document type locally.
                </p>
                <p>
                    Unsure how to fix a merge conflict, then <a href="https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/" target="_blank">GitHub has a great guide on this</a>
                </p>
            </div>

            <div ng-switch-default>
                <h4 class="bold color-red">An error occurred</h4>
                <p>
                    The {{exception.EnvironmentName || 'source'}} environment has thrown a
                    <em>{{exception.ExceptionType || uiException.ClassName || 'unknown exception'}}</em> with message:
                    <em>{{exception.ExceptionMessage || exception.Message || '(empty)'}}</em>
                    <span ng-if="innerException !== exception">
                        It might have been caused by an inner <em>{{innerException.ExceptionType}}</em> with message:
                        <em>{{innerException.ExceptionMessage || innerException.Message || '(empty)'}}</em>
                    </span>
                </p>
                <div ng-if="exceptionUdis.length>0">
                    <p>The following artifacts might be involved:</p>
                    <ul ng-repeat="udi in exceptionUdis">
                        <li>{{udi}}</li>
                    </ul>
                </div>
                <p>The <em>technical details</em> may contain more information.</p>
            </div>
        </div>
    </div>

    <div ng-if="status === 'cancelled'">
        <h4 class="bold">Task was cancelled</h4>
        <p>The task was cancelled during execution.</p>
    </div>

    <div ng-if="status === 'timedOut'">
        <h4 class="bold">Task timed out</h4>
        <p>The task timed out.</p>
    </div>

    <p>
        <small><strong>Time:</strong> {{ timestamp }}</small>
        <span ng-if="showDebug">
            <br/>
            <small><strong>Server Time:</strong> {{ serverTimestamp }}</small>
        </span>
    </p>

    <umb-button
        type="button"
        button-style="success"
        action="onBack()"
        label="Okay">
    </umb-button>

    <umb-button
        type="button"
        button-style="link"
        action="onDebug()"
        label="View technical details">
    </umb-button>
</div>
